provider-bitcoin/src/main/java/network/arkane/provider/bitcoin/sign/BitcoinTransactionFactory.java, provider-bitcoin/src/main/java/network/arkane/provider/bitcoin/sign/BitcoinTransactionSignable.java, provider-bitcoin/src/test/java/network/arkane/provider/bitcoin/sign/BitcoinTransactionFactoryTest.java
[[ARKANE-489]](https://arkane.atlassian.net/browse/ARKANE-489)
=> ARKANE-489

provider-litecoin/src/main/java/network/arkane/provider/litecoin/wallet/exporting/LitecoinKeyExporter.java, provider-litecoin/src/main/java/network/arkane/provider/litecoin/wallet/generation/LitecoinKeystore.java, provider-litecoin/src/test/java/network/arkane/provider/litecoin/wallet/exporting/LitecoinKeyExporterTest.java
[ARKANE-621]
[ARKANE-621]: https://arkane.atlassian.net/browse/ARKANE-621
=> [ARKANE-621] correctly export litecoin

provider-litecoin/src/main/java/network/arkane/provider/litecoin/bitcoinj/LitecoinParams.java, provider-litecoin/src/test/java/network/arkane/provider/litecoin/extraction/LitecoinWifExtractorTest.java
[ARKANE-622]
[ARKANE-622]: https://arkane.atlassian.net/browse/ARKANE-622
=> [ARKANE-622] using the correct headers for litecoin

blockcypher/pom.xml, integrationtests/pom.xml, pom.xml, provider-aeternity/pom.xml, provider-aeternity/src/main/java/network/arkane/provider/balance/AeternityBalanceGateway.java, provider-api/pom.xml, provider-api/src/main/java/network/arkane/provider/balance/BalanceGateway.java, provider-api/src/main/java/network/arkane/provider/balance/domain/Balance.java, provider-api/src/main/java/network/arkane/provider/balance/domain/TokenBalance.java, provider-autoconfiguration/pom.xml, provider-bitcoin/pom.xml, provider-bitcoin/src/main/java/network/arkane/provider/bitcoin/balance/BitcoinBalanceGateway.java, provider-ethereum/pom.xml, provider-ethereum/src/main/java/network/arkane/provider/balance/EthereumBalanceGateway.java, provider-gochain/pom.xml, provider-gochain/src/main/java/network/arkane/provider/balance/GochainBalanceGateway.java, provider-litecoin/pom.xml, provider-litecoin/src/main/java/network/arkane/provider/litecoin/balance/LitecoinBalanceGateway.java, provider-vechain/pom.xml, provider-vechain/src/main/java/network/arkane/provider/balance/VechainBalanceGateway.java
[ARKANE-633]
[ARKANE-633]: https://arkane.atlassian.net/browse/ARKANE-633
=> Arkane 633

provider-aeternity/README.md, provider-aeternity/pom.xml, provider-aeternity/src/main/java/network/arkane/provider/sign/AeternitySpendTransactionSigner.java
- fees (gas costs) are now automatically calculated by the SDK when `null` is provided as fee
=> updated to aepp-sdk-java:1.1.0

provider-vechain/src/main/java/network/arkane/provider/sign/VechainTransactionSigner.java
[ARKANE-682]
[ARKANE-682]: https://arkane.atlassian.net/browse/ARKANE-682
=> ARKANE-682 ignore 0x data

provider-ethereum/src/main/java/network/arkane/provider/sign/EthereumRawSigner.java, provider-ethereum/src/test/java/network/arkane/provider/sign/EthereumRawSignerTest.java
[ARKANE-743]
[ARKANE-743]: https://arkane.atlassian.net/browse/ARKANE-743
=> ARKANE-743 fix hex issue

provider-gochain/src/main/java/network/arkane/provider/bridge/GochainTransactionGateway.java, provider-litecoin/src/main/java/network/arkane/provider/litecoin/wallet/exporting/LitecoinKeyExporter.java, provider-tron/src/main/java/network/arkane/provider/tron/wallet/exporting/TronKeystoreExporter.java
[ARKANE-694]
[ARKANE-694]: https://arkane.atlassian.net/browse/ARKANE-694
=> update some error codes

provider-tron/pom.xml, provider-tron/src/main/java/network/arkane/provider/tron/sign/TrxRawSignable.java, provider-tron/src/main/java/network/arkane/provider/tron/sign/TrxRawSigner.java
[ARKANE-744]
[ARKANE-744]: https://arkane.atlassian.net/browse/ARKANE-744
=> ARKANE-744 Tron raw signer

blockcypher/pom.xml, integrationtests/pom.xml, pom.xml, provider-aeternity/pom.xml, provider-aeternity/src/main/java/network/arkane/provider/AeternityServiceAutoConfiguration.java, provider-aeternity/src/main/java/network/arkane/provider/balance/AeternityBalanceGateway.java, provider-aeternity/src/main/java/network/arkane/provider/bridge/AeternityTransactionGateway.java, provider-aeternity/src/main/java/network/arkane/provider/sign/AeternitySpendTransactionSigner.java, provider-api/pom.xml, provider-autoconfiguration/pom.xml, provider-bitcoin/pom.xml, provider-ethereum/pom.xml, provider-gochain/pom.xml, provider-litecoin/pom.xml, provider-tron/pom.xml, provider-vechain/pom.xml
[ARKANE-779]
[ARKANE-779]: https://arkane.atlassian.net/browse/ARKANE-779
=> Arkane 779

blockcypher/pom.xml, integrationtests/pom.xml, pom.xml, provider-aeternity/pom.xml, provider-aeternity/src/main/java/network/arkane/provider/bridge/AeternityTransactionGateway.java, provider-api/pom.xml, provider-api/src/main/java/network/arkane/provider/bridge/TransactionGateway.java, provider-autoconfiguration/pom.xml, provider-bitcoin/pom.xml, provider-bitcoin/src/main/java/network/arkane/provider/bitcoin/bridge/BitcoinTransactionGateway.java, provider-bitcoin/src/test/java/network/arkane/provider/bitcoin/bridge/BitcoinTransactionGatewayTest.java, provider-ethereum/pom.xml, provider-ethereum/src/main/java/network/arkane/provider/bridge/EthereumTransactionGateway.java, provider-ethereum/src/main/java/network/arkane/provider/gateway/EthereumWeb3JGateway.java, provider-ethereum/src/test/java/network/arkane/provider/bridge/EthereumTransactionGatewayTest.java, provider-gochain/pom.xml, provider-gochain/src/main/java/network/arkane/provider/bridge/GochainTransactionGateway.java, provider-gochain/src/test/java/network/arkane/provider/bridge/GochainTransactionGatewayTest.java, provider-litecoin/pom.xml, provider-litecoin/src/main/java/network/arkane/provider/litecoin/bridge/LitecoinTransactionGateway.java, provider-litecoin/src/test/java/network/arkane/provider/litecoin/bridge/LitecoinTransactionGatewayTest.java, provider-tron/pom.xml, provider-tron/src/main/java/network/arkane/provider/tron/bridge/TronTransactionGateway.java, provider-vechain/pom.xml, provider-vechain/src/main/java/network/arkane/provider/bridge/VechainTransactionGateway.java, provider-vechain/src/test/java/network/arkane/provider/bridge/VechainTransactionGatewayTest.java
[ARKANE-820]
[ARKANE-820]: https://arkane.atlassian.net/browse/ARKANE-820
=> sidechains

provider-ethereum/src/main/java/network/arkane/provider/Web3AutoConfiguration.java, provider-ethereum/src/main/java/network/arkane/provider/gateway/EthereumWeb3JGateway.java, provider-ethereum/src/main/java/network/arkane/provider/gateway/EthereumWeb3JGatewayFactory.java
[ARKANE-865]
[ARKANE-865]: https://arkane.atlassian.net/browse/ARKANE-865
=> ARKANE-865 - Fix nonce issue for sidechains

provider-ethereum/src/main/java/network/arkane/provider/sign/EthereumRawSigner.java, provider-ethereum/src/test/java/network/arkane/provider/sign/EthereumRawSignerTest.java
[ARKANE-894]
[ARKANE-894]: https://arkane.atlassian.net/browse/ARKANE-894
=> ARKANE-894

provider-aeternity/README.md, provider-aeternity/pom.xml, provider-aeternity/src/main/java/network/arkane/provider/AeternityServiceAutoConfiguration.java, provider-aeternity/src/main/java/network/arkane/provider/sign/AeternityContractCallSignable.java, provider-aeternity/src/main/java/network/arkane/provider/sign/AeternityContractCallTransactionSigner.java, provider-aeternity/src/main/java/network/arkane/provider/sign/AeternityContractCreateSignable.java, provider-aeternity/src/main/java/network/arkane/provider/sign/AeternityContractCreateTransactionSigner.java
this pull request should ship all functionalities that are required to integrate smart contract support for æternity into Arkane.
@mitch-lbw should confirm before accepting the pull-request.
if you have any questions feel free to ask. we will publish the sdk documentation soon on https://kryptokrauts.gitbook.io/aepp-sdk-java/
=> add smart contract support for æternity

provider-tron/src/main/java/network/arkane/provider/tron/sign/TronRawSigner.java, provider-tron/src/test/java/network/arkane/provider/tron/sign/TronRawSignerTest.java
[ARKANE-994]
[ARKANE-994]: https://arkane.atlassian.net/browse/ARKANE-994
=> ARKANE-994 produce same output as tronweb/tronlink

blockcypher/pom.xml, integrationtests/pom.xml, integrationtests/src/test/java/network/arkane/provider/opensea/OpenSeaClientIT.java, opensea/pom.xml, opensea/src/main/java/network/arkane/provider/opensea/OpenSeaClient.java, opensea/src/main/java/network/arkane/provider/opensea/OpenSeaGateway.java, opensea/src/test/java/network/arkane/provider/opensea/OpenSeaGatewayTest.java, pom.xml, provider-aeternity/pom.xml, provider-api/pom.xml, provider-api/src/main/java/network/arkane/provider/nonfungible/NonFungibleGateway.java, provider-api/src/main/java/network/arkane/provider/nonfungible/domain/NonFungibleAsset.java, provider-api/src/test/java/network/arkane/provider/nonfungible/domain/NonFungibleAssetMother.java, provider-autoconfiguration/pom.xml, provider-bitcoin/pom.xml, provider-ethereum/pom.xml, provider-ethereum/src/main/java/network/arkane/provider/nonfungable/EthereumNonFungibleGateway.java, provider-ethereum/src/main/java/network/arkane/provider/nonfungable/OpenSeaAssetToNonFungibleAssetMapper.java, provider-ethereum/src/main/java/network/arkane/provider/nonfungable/OpenSeaContractToNonFungibleContractMapper.java, provider-ethereum/src/test/java/network/arkane/provider/nonfungable/EthereumNonFungibleGatewayTest.java, provider-ethereum/src/test/java/network/arkane/provider/nonfungable/OpenSeaAssetToNonFungibleAssetMapperTest.java, provider-ethereum/src/test/java/network/arkane/provider/nonfungable/OpenSeaContractToNonFungibleContractMapperTest.java, provider-gochain/pom.xml, provider-litecoin/pom.xml, provider-neo/pom.xml, provider-tron/pom.xml, provider-vechain/pom.xml
[ARKANE-1003]
[ARKANE-1003]: https://arkane.atlassian.net/browse/ARKANE-1003
=> ARKANE-1003

opensea/src/main/java/network/arkane/provider/opensea/OpenSeaClient.java
[ARKANE-993]
[ARKANE-993]: https://arkane.atlassian.net/browse/ARKANE-993
=> ARKANE-993 opensea limits to 300

pom.xml, provider-litecoin/pom.xml, provider-neo/pom.xml
[ARKANE-1310]
[ARKANE-1310]: https://arkane.atlassian.net/browse/ARKANE-1310
=> ARKANE-1310 update neow3j dependency

provider-api/src/main/java/network/arkane/provider/exceptions/ArkaneException.java, provider-ethereum/src/test/java/network/arkane/provider/bridge/EthereumTransactionGatewayTest.java, provider-litecoin/src/test/java/network/arkane/provider/litecoin/address/LitecoinP2SHConverterTest.java, provider-litecoin/src/test/java/network/arkane/provider/litecoin/sign/LitecoinTransactionFactoryTest.java, provider-litecoin/src/test/java/network/arkane/provider/litecoin/sign/LitecoinTransactionSignerTest.java, provider-litecoin/src/test/java/network/arkane/provider/litecoin/wallet/exporting/LitecoinKeyExporterTest.java, provider-vechain/src/main/java/network/arkane/provider/utils/RawTransactionFactory.java, provider-vechain/src/test/java/network/arkane/provider/bridge/VechainTransactionGatewayTest.java
[ARKANE-1569]
[ARKANE-1569]: https://arkane.atlassian.net/browse/ARKANE-1569
=> ARKANE-1569

provider-aeternity/README.md, provider-aeternity/pom.xml, provider-aeternity/src/main/java/network/arkane/provider/aeternity/sign/AeternityContractCallTransactionSigner.java, provider-aeternity/src/main/java/network/arkane/provider/aeternity/sign/AeternityContractCreateTransactionSigner.java, provider-aeternity/src/main/java/network/arkane/provider/aeternity/sign/AeternitySpendTransactionSigner.java
for new SDK versions we introduced a ResultWrapper to provide better error-handling. for creating unsigned transactions a proper error handling isn't mandatory. but for other actions it is useful.
=> update to aepp-sdk-java v2.2.1

Jenkinsfile, provider-evm/src/main/java/network/arkane/provider/nonfungible/MetaDataParser.java, provider-evm/src/main/java/network/arkane/provider/nonfungible/NonFungibleMetaData.java, provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeByExtensionMapper.java, provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparator.java, provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationUrlParser.java, provider-evm/src/main/java/network/arkane/provider/nonfungible/animationtype/AnimationUrlParserFactory.java, provider-evm/src/test/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeByExtensionMapperTest.java, provider-evm/src/test/java/network/arkane/provider/nonfungible/animationtype/AnimationTypeComparatorTest.java, provider-evm/src/test/java/network/arkane/provider/nonfungible/animationtype/AnimationUrlParserTest.java
[ARKANE-2367]
[ARKANE-2367]: https://arkane.atlassian.net/browse/ARKANE-2367
=> feat(ARKANE-2367): determine correct animationType for unknown types

provider-evm/src/main/java/network/arkane/provider/nonfungible/NonFungibleMetaData.java
[ARKANE-2367]
[ARKANE-2367]: https://arkane.atlassian.net/browse/ARKANE-2367
=> feat(ARKANE-2367): Also parse 'unknown's from 'animationUrls' property

provider-api-model/src/main/java/network/arkane/provider/tx/TxInfo.java, provider-api/src/main/java/network/arkane/provider/tx/HasReachedFinalityService.java, provider-api/src/main/java/network/arkane/provider/tx/TransactionConfigurationProperties.java, provider-avac/src/main/java/network/arkane/provider/avac/tx/AvacTransactionInfoService.java, provider-bitcoin/src/main/java/network/arkane/provider/bitcoin/tx/BitcoinTransactionInfoService.java, provider-bsc/src/main/java/network/arkane/provider/bsc/tx/BscTransactionInfoService.java, provider-ethereum/src/main/java/network/arkane/provider/tx/EthereumTransactionInfoService.java, provider-ethereum/src/test/java/network/arkane/provider/tx/EthereumTransactionInfoServiceIntegrationTest.java, provider-evm/src/main/java/network/arkane/provider/tx/EvmTransactionInfoService.java, provider-evm/src/main/java/network/arkane/provider/tx/EvmTxInfo.java, provider-gochain/src/main/java/network/arkane/provider/tx/GochainTransactionInfoService.java, provider-hedera/src/main/java/network/arkane/provider/hedera/tx/HederaTransactionInfoService.java, provider-hedera/src/main/java/network/arkane/provider/hedera/tx/HederaTxInfo.java, provider-matic/src/main/java/network/arkane/provider/tx/MaticTransactionInfoService.java, provider-tron/src/main/java/network/arkane/provider/tron/tx/TronTxInfo.java, provider-vechain/src/main/java/network/arkane/provider/tx/VechainTransactionInfoService.java, provider-vechain/src/main/java/network/arkane/provider/tx/VechainTxInfo.java, provider-vechain/src/test/java/network/arkane/provider/tx/VechainTransactionInfoServiceIntegrationTest.java
[VENLY-2824]
[VENLY-2824]: https://arkane.atlassian.net/browse/VENLY-2824?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> VENLY-2824 - Move hasReachedFinality to blockchain-providers
